// ====================================================================
// L.U.N.A. MCP Server Registry - Curated List of Popular MCP Servers
// ====================================================================

export interface MCPRegistryItem {
    id: string;
    name: string;
    description: string;
    descriptionKo?: string;
    descriptionJa?: string;
    category: 'productivity' | 'search' | 'development' | 'communication' | 'storage' | 'ai' | 'utility';
    icon: string;
    author: string;
    stars?: number;
    installType: 'npm' | 'pip' | 'binary' | 'docker';
    command: string;
    args: string[];
    env?: Record<string, string>;
    envRequired?: string[];
    homepage?: string;
    featured?: boolean;
}

export const mcpRegistry: MCPRegistryItem[] = [
    // === Featured ===
    {
        id: 'filesystem',
        name: 'Filesystem',
        description: 'Read, write, and manage files on the local filesystem',
        descriptionKo: '로컬 파일시스템에서 파일 읽기, 쓰기, 관리',
        descriptionJa: 'ローカルファイルシステムでファイルを読み書き・管理',
        category: 'storage',
        icon: '📁',
        author: 'Anthropic',
        stars: 5000,
        installType: 'npm',
        command: 'npx',
        args: ['-y', '@modelcontextprotocol/server-filesystem', '/'],
        featured: true,
        homepage: 'https://github.com/modelcontextprotocol/servers',
    },
    {
        id: 'brave-search',
        name: 'Brave Search',
        description: 'Web search using Brave Search API',
        descriptionKo: 'Brave Search API를 사용한 웹 검색',
        descriptionJa: 'Brave Search APIを使用したウェブ検索',
        category: 'search',
        icon: '🦁',
        author: 'Anthropic',
        stars: 3500,
        installType: 'npm',
        command: 'npx',
        args: ['-y', '@modelcontextprotocol/server-brave-search'],
        env: { BRAVE_API_KEY: '' },
        envRequired: ['BRAVE_API_KEY'],
        featured: true,
        homepage: 'https://github.com/modelcontextprotocol/servers',
    },
    {
        id: 'github',
        name: 'GitHub',
        description: 'Interact with GitHub repositories, issues, and pull requests',
        descriptionKo: 'GitHub 저장소, 이슈, PR 관리',
        descriptionJa: 'GitHubリポジトリ、イシュー、PRの操作',
        category: 'development',
        icon: '🐙',
        author: 'Anthropic',
        stars: 4200,
        installType: 'npm',
        command: 'npx',
        args: ['-y', '@modelcontextprotocol/server-github'],
        env: { GITHUB_PERSONAL_ACCESS_TOKEN: '' },
        envRequired: ['GITHUB_PERSONAL_ACCESS_TOKEN'],
        featured: true,
        homepage: 'https://github.com/modelcontextprotocol/servers',
    },

    // === Search ===
    {
        id: 'google-search',
        name: 'Google Search',
        description: 'Web search using Google Custom Search API',
        descriptionKo: 'Google Custom Search API를 사용한 웹 검색',
        descriptionJa: 'Google Custom Search APIを使用したウェブ検索',
        category: 'search',
        icon: '🔍',
        author: 'Community',
        installType: 'npm',
        command: 'npx',
        args: ['-y', '@anthropics/mcp-server-google-search'],
        env: { GOOGLE_API_KEY: '', GOOGLE_CSE_ID: '' },
        envRequired: ['GOOGLE_API_KEY', 'GOOGLE_CSE_ID'],
    },
    {
        id: 'duckduckgo',
        name: 'DuckDuckGo',
        description: 'Privacy-focused web search',
        descriptionKo: '프라이버시 중심 웹 검색',
        descriptionJa: 'プライバシー重視のウェブ検索',
        category: 'search',
        icon: '🦆',
        author: 'Community',
        installType: 'pip',
        command: 'uvx',
        args: ['mcp-server-duckduckgo'],
    },

    // === Productivity ===
    {
        id: 'notion',
        name: 'Notion',
        description: 'Read and write Notion pages and databases',
        descriptionKo: 'Notion 페이지와 데이터베이스 읽기/쓰기',
        descriptionJa: 'Notionページとデータベースの読み書き',
        category: 'productivity',
        icon: '📝',
        author: 'Community',
        stars: 2800,
        installType: 'npm',
        command: 'npx',
        args: ['-y', '@notionhq/mcp-server-notion'],
        env: { NOTION_API_KEY: '' },
        envRequired: ['NOTION_API_KEY'],
    },
    {
        id: 'google-calendar',
        name: 'Google Calendar',
        description: 'Manage Google Calendar events',
        descriptionKo: 'Google Calendar 일정 관리',
        descriptionJa: 'Googleカレンダーのイベント管理',
        category: 'productivity',
        icon: '📅',
        author: 'Community',
        installType: 'npm',
        command: 'npx',
        args: ['-y', 'mcp-server-google-calendar'],
        env: { GOOGLE_CLIENT_ID: '', GOOGLE_CLIENT_SECRET: '' },
        envRequired: ['GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET'],
    },
    {
        id: 'todoist',
        name: 'Todoist',
        description: 'Manage Todoist tasks and projects',
        descriptionKo: 'Todoist 작업 및 프로젝트 관리',
        descriptionJa: 'Todoistタスクとプロジェクトの管理',
        category: 'productivity',
        icon: '✅',
        author: 'Community',
        installType: 'npm',
        command: 'npx',
        args: ['-y', 'mcp-server-todoist'],
        env: { TODOIST_API_TOKEN: '' },
        envRequired: ['TODOIST_API_TOKEN'],
    },

    // === Communication ===
    {
        id: 'slack',
        name: 'Slack',
        description: 'Send and read Slack messages',
        descriptionKo: 'Slack 메시지 전송 및 읽기',
        descriptionJa: 'Slackメッセージの送受信',
        category: 'communication',
        icon: '💬',
        author: 'Anthropic',
        stars: 2100,
        installType: 'npm',
        command: 'npx',
        args: ['-y', '@modelcontextprotocol/server-slack'],
        env: { SLACK_BOT_TOKEN: '' },
        envRequired: ['SLACK_BOT_TOKEN'],
    },
    {
        id: 'discord',
        name: 'Discord',
        description: 'Interact with Discord servers and channels',
        descriptionKo: 'Discord 서버 및 채널 상호작용',
        descriptionJa: 'Discordサーバーとチャンネルの操作',
        category: 'communication',
        icon: '🎮',
        author: 'Community',
        installType: 'npm',
        command: 'npx',
        args: ['-y', 'mcp-server-discord'],
        env: { DISCORD_BOT_TOKEN: '' },
        envRequired: ['DISCORD_BOT_TOKEN'],
    },

    // === Storage ===
    {
        id: 'google-drive',
        name: 'Google Drive',
        description: 'Access and manage Google Drive files',
        descriptionKo: 'Google Drive 파일 액세스 및 관리',
        descriptionJa: 'Google Driveファイルのアクセスと管理',
        category: 'storage',
        icon: '📂',
        author: 'Anthropic',
        stars: 1800,
        installType: 'npm',
        command: 'npx',
        args: ['-y', '@modelcontextprotocol/server-google-drive'],
        env: { GOOGLE_CLIENT_ID: '', GOOGLE_CLIENT_SECRET: '' },
        envRequired: ['GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET'],
    },
    {
        id: 'postgres',
        name: 'PostgreSQL',
        description: 'Query and manage PostgreSQL databases',
        descriptionKo: 'PostgreSQL 데이터베이스 쿼리 및 관리',
        descriptionJa: 'PostgreSQLデータベースのクエリと管理',
        category: 'storage',
        icon: '🐘',
        author: 'Anthropic',
        stars: 2500,
        installType: 'npm',
        command: 'npx',
        args: ['-y', '@modelcontextprotocol/server-postgres'],
        env: { POSTGRES_CONNECTION_STRING: '' },
        envRequired: ['POSTGRES_CONNECTION_STRING'],
    },
    {
        id: 'sqlite',
        name: 'SQLite',
        description: 'Query and manage SQLite databases',
        descriptionKo: 'SQLite 데이터베이스 쿼리 및 관리',
        descriptionJa: 'SQLiteデータベースのクエリと管理',
        category: 'storage',
        icon: '💾',
        author: 'Anthropic',
        stars: 1500,
        installType: 'npm',
        command: 'npx',
        args: ['-y', '@modelcontextprotocol/server-sqlite', '--db-path', './data.db'],
    },

    // === Development ===
    {
        id: 'git',
        name: 'Git',
        description: 'Git repository operations',
        descriptionKo: 'Git 저장소 작업',
        descriptionJa: 'Gitリポジトリ操作',
        category: 'development',
        icon: '🔀',
        author: 'Community',
        installType: 'pip',
        command: 'uvx',
        args: ['mcp-server-git'],
    },
    {
        id: 'docker',
        name: 'Docker',
        description: 'Manage Docker containers and images',
        descriptionKo: 'Docker 컨테이너 및 이미지 관리',
        descriptionJa: 'Dockerコンテナとイメージの管理',
        category: 'development',
        icon: '🐳',
        author: 'Community',
        installType: 'docker',
        command: 'docker',
        args: ['run', '--rm', '-i', '-v', '/var/run/docker.sock:/var/run/docker.sock', 'mcp/docker'],
    },

    // === AI ===
    {
        id: 'openai',
        name: 'OpenAI',
        description: 'Use OpenAI models and APIs',
        descriptionKo: 'OpenAI 모델 및 API 사용',
        descriptionJa: 'OpenAIモデルとAPIの利用',
        category: 'ai',
        icon: '🤖',
        author: 'Community',
        installType: 'npm',
        command: 'npx',
        args: ['-y', 'mcp-server-openai'],
        env: { OPENAI_API_KEY: '' },
        envRequired: ['OPENAI_API_KEY'],
    },

    // === Utility ===
    {
        id: 'fetch',
        name: 'Fetch',
        description: 'Fetch and parse web content',
        descriptionKo: '웹 콘텐츠 가져오기 및 파싱',
        descriptionJa: 'Webコンテンツの取得とパース',
        category: 'utility',
        icon: '🌐',
        author: 'Anthropic',
        stars: 3000,
        installType: 'npm',
        command: 'npx',
        args: ['-y', '@modelcontextprotocol/server-fetch'],
        featured: true,
    },
    {
        id: 'puppeteer',
        name: 'Puppeteer',
        description: 'Browser automation and web scraping',
        descriptionKo: '브라우저 자동화 및 웹 스크래핑',
        descriptionJa: 'ブラウザ自動化とWebスクレイピング',
        category: 'utility',
        icon: '🎭',
        author: 'Anthropic',
        stars: 2200,
        installType: 'npm',
        command: 'npx',
        args: ['-y', '@modelcontextprotocol/server-puppeteer'],
    },
    {
        id: 'time',
        name: 'Time',
        description: 'Get current time and timezone info',
        descriptionKo: '현재 시간 및 시간대 정보',
        descriptionJa: '現在時刻とタイムゾーン情報',
        category: 'utility',
        icon: '⏰',
        author: 'Community',
        installType: 'pip',
        command: 'uvx',
        args: ['mcp-server-time'],
    },
    {
        id: 'memory',
        name: 'Memory',
        description: 'Persistent memory storage for conversations',
        descriptionKo: '대화를 위한 영구 메모리 저장소',
        descriptionJa: '会話のための永続メモリストレージ',
        category: 'utility',
        icon: '🧠',
        author: 'Anthropic',
        stars: 1900,
        installType: 'npm',
        command: 'npx',
        args: ['-y', '@modelcontextprotocol/server-memory'],
    },
];

export const categoryLabels: Record<string, { en: string; ko: string; ja: string; icon: string }> = {
    productivity: { en: 'Productivity', ko: '생산성', ja: '生産性', icon: '📊' },
    search: { en: 'Search', ko: '검색', ja: '検索', icon: '🔍' },
    development: { en: 'Development', ko: '개발', ja: '開発', icon: '💻' },
    communication: { en: 'Communication', ko: '커뮤니케이션', ja: 'コミュニケーション', icon: '💬' },
    storage: { en: 'Storage', ko: '저장소', ja: 'ストレージ', icon: '💾' },
    ai: { en: 'AI', ko: 'AI', ja: 'AI', icon: '🤖' },
    utility: { en: 'Utility', ko: '유틸리티', ja: 'ユーティリティ', icon: '🔧' },
};
